config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :teachers, controllers: {
    sessions: "teachers/sessions",
    passwords:  'teachers/passwords',
    registrations: 'teachers/registrations'
  }
  devise_for :students, controllers: {
    sessions:      'students/sessions',
    passwords:     'students/passwords',
    registrations: 'students/registrations'
  }
  resources :teachers, only: [:edit,:update,:show]
  resources :students, only: [:edit,:update,:show,:index] do
    member do
    resources :student_records
    end
  end
  get 'messages/index'
  resources :rooms,only: [:index,:new,:create,:destroy] do
  resources :messages,only: [:new,:create,:index]
  end
  get 'contacts/index'
  resources :teacher_rooms,only: [:index,:new,:create,:destroy] do
    resources :contacts,only: [:new,:create,:index]
  end
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :room_students
  has_many :rooms, through: :room_students,dependent: :destroy
  has_many :messages
  belongs_to :teacher
  has_many :teacher_rooms,dependent: :destroy
  has_one_attached :image,dependent: :destroy
  validates :status_message,length: { maximum: 50 }
  has_many :student_records,dependent: :destroy

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,}+\z/i.freeze
  validates_format_of :password, on: :create, with: PASSWORD_REGEX, message: 'は半角の英字・数字を両方含んでください'
end

app/controllers/students/confirmations_controller.rb
# frozen_string_literal: true

class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_student!, except: [:index]
  before_action :authenticate_teacher!, only: [:index]

  def show
  end

  def edit
  end

  def update
    if current_student.update(student_params)
      binding.pry
      redirect_to rooms_path
    else
      render :edit
    end
  end

  def index
    @students = Student.where(teacher_id: current_teacher.id)
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :image, :status_message,:key)
  end
end

app/views/students/edit.html.erb
<div class='account-page' id='account-page'>
<div class="piano__image-wrap">
<div class="piano__image">
  <div class='account-page__inner '>
    <div class='account-page__header'>
      <h2>アカウント編集</h2>
    </div>
    <div class='user-form'>
    
      <%= form_with model: current_student, local: true do |f|%>
      <%=render 'layouts/error_messages', model: f.object%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :image, "プロフィール画像"%>
          </div>
          <div class='field-input'>
            <%=f.file_field :image,class: "profile-image-field"%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :status_message, "メッセージ(50字以内)"%>
          </div>
          <div class='field-input'>
            <%= f.text_area :status_message%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :key, "アカウントを非公開にする"%>
            <%= f.check_box :key,{}, "true","false"%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>
</div>

app/views/students/index.html.erb
<div class="wrapper">
  <div class="account-page">
    <div class="students-index-page">
    <h1>- 生徒情報一覧 -</h1>
      <%@students.each do |student|%>
        <div class='account-info'>
          
          <div class="students-index__account-info-data">
          
          <div class="account-info-data__left">
            <%=image_tag student.image.variant(resize: '70x70') , class: "user-image" if student.image.attached?%>
          </div>

          <div class="account-info-data__right">
          <h1> <%=student.name%>さん</h1>
          <p>メッセージ： <%=student.status_message%></p>
          </div>
          <div>
         <%=link_to "＞＞詳細ページへ" ,student_records_path(id: student.id),class:"move-show"%>
         <%=link_to "＞＞非表示にする" ,student_registration_path(id: student.id), method: :delete,class: 'destroy_user',data: {confirm: "非表示にしますか？"} ,class:"move-show delete"%>
           </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/students/show.html.erb
<div class="wrapper">
<div class="piano__image-wrap">
<div class="piano__image">

<div class='account-page'>
  <div class='account-page__inner'>
    <div class='account-page__header'>
      <h2>登録情報</h2>
    </div>

   <div class='account-info'>
      <div class="account-info-data">   
      <div class="account-info-data__left">
        <%=image_tag current_student.image.variant(resize: '70x70') , class: "user-image" if current_student.image.attached?%>
      </div>

      <div class="account-info-data__right">
      <p>名前： <%=current_student.name%></p>
      <p>メールアドレス： <%=current_student.email%></p>
      <p>メッセージ： <%=current_student.status_message%></p>
      <%if current_student.key == true%>
      <p>アカウント： 非公開</p>
      <%else%>
      <p>アカウント： 公開</p>
      <%end%>
      </div>
      </div>
    </div>
    <div class="move">
     <%= link_to "編\b\b集", edit_student_path,class: 'logout'%>
     <%= link_to "ログアウト", destroy_student_session_path, method: :delete,class: 'logout'%>
     </div>
     <%=link_to "＞＞アカウントを削除する", student_registration_path, method: :delete,class: 'destroy_user',data: {confirm: "本当に削除しますか？"}  %>
</div>
</div>
</div>
</div>
</div>