config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :teachers, controllers: {
    sessions: "teachers/sessions",
    passwords:  'teachers/passwords',
    registrations: 'teachers/registrations'
  }
  devise_for :students, controllers: {
    sessions:      'students/sessions',
    passwords:     'students/passwords',
    registrations: 'students/registrations'
  }
  resources :teachers, only: [:edit,:update,:show]
  resources :students, only: [:edit,:update,:show,:index] do
    member do
    resources :student_records
    end
  end
  get 'messages/index'
  resources :rooms,only: [:index,:new,:create,:destroy] do
  resources :messages,only: [:new,:create,:index]
  end
  get 'contacts/index'
  resources :teacher_rooms,only: [:index,:new,:create,:destroy] do
    resources :contacts,only: [:new,:create,:index]
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :teacher_room
  validates :content, presence: true, unless: :was_attached?
  has_one_attached :image

  private

  def was_attached?
    image.attached?
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_any!

  def index
    @teacher_room = TeacherRoom.find(params[:teacher_room_id])
    @contact = Contact.new
    @contacts = @teacher_room.contacts
  end

  def create
    @teacher_room = TeacherRoom.find(params[:teacher_room_id])
    @contact = Contact.new(contact_params)
    if teacher_signed_in?
      @contact.is_student = false
    elsif student_signed_in?
      @contact.is_student = true
    end
    @contact.teacher_room_id = @teacher_room.id

    if @contact.save
      redirect_to teacher_room_contacts_path(params[:teacher_room_id])
    else
      render :index
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:content, :image)
  end

  def authenticate_any!
    if student_signed_in?
    elsif authenticate_teacher!
    end
  end
end

app/views/contacts/_contact.html.erb
<%if teacher_signed_in?%>
<%if contact.is_student%>
<div class="message-wrapper">
    <div class="your-message">
      <div class="your-name-date">
        <div class="name"> 
         <%=@teacher_room.student.name%>
        </div>
        <div class="date"> 
          <%=contact.created_at.strftime("%Y年%m月%d日%H時%M分") %>
        </div>
      </div>
       <%if contact.content != ""%>
      <div class="text">
        <%=simple_format(contact.content)%>
      </div>
      <%end%>
      <div class='message-image'>
      <%=image_tag contact.image.variant(resize: '300x300'), class: 'message-img' if contact.image.attached?%>
      </div>
    </div>
  </div>

  <%else%>
<div class="message-wrapper">
     <div class="my-message">
      <div class="my-name-date">
        <div class="name">
          
          <%=@teacher_room.teacher.name%>
        
        </div>
        <div class="date">
          <%= contact.created_at.strftime("%Y年%m月%d日%H時%M分")%>
        </div>
      </div>
      <%if contact.content != ""%>
      <div class="text">
        <%=simple_format(contact.content)%>
      </div>
      <%end%>
      <div class='message-image'>
      <%=image_tag contact.image.variant(resize: '300x300'), class: 'message-img' if contact.image.attached? %>
      </div>
    </div>
    </div>
  <%end%>

  <%else%>
  <%if contact.is_student%>
  <div class="message-wrapper">
     <div class="my-message">
      <div class="my-name-date">
        <div class="name">
          
          <%=@teacher_room.student.name%>
        
        </div>
        <div class="date">
          <%= contact.created_at.strftime("%Y年%m月%d日%H時%M分")%>
        </div>
      </div>
      <%if contact.content != ""%>
      <div class="text">
        <%=simple_format(contact.content)%>
      </div>
      <%end%>
      <div class='message-image'>
      <%=image_tag contact.image.variant(resize: '300x300'), class: 'message-img' if contact.image.attached?%>
      </div>

    </div>
    </div>
    <%else%>
<div class="message-wrapper">
    <div class="your-message">
      <div class="your-name-date">
        <div class="name"> 
         <%=@teacher_room.teacher.name%>
        </div>
        <div class="date"> 
          <%=contact.created_at.strftime("%Y年%m月%d日%H時%M分") %>
        </div>
      </div>
      <%if contact.content != ""%>
      <div class="text">
        <%=simple_format(contact.content)%>
      </div>
      <%end%>
      <div class='message-image'>
      <%=image_tag contact.image.variant(resize: '300x300'), class: 'message-img' if contact.image.attached?%>
      </div>
    </div>
  </div>

  <%end%>
  

  <%end%>

  

app/views/contacts/_main_chat.html.erb
<div class="main">
  <div class="chat-header">
    <div class="left-header">
      <div class="chat-title">
      <%= @teacher_room.name%>
      </div>
    </div>
    <div class="right-header">
      <%= @teacher_room.student.name%>
    </div>
  </div>

  <div class="messages">
      <%=render partial: 'contact', collection: @contacts%>
  </div>

 <%=form_with model:[@teacher_room,@contact], class:"form",local: true do |f|%>
    <div class="form-input">
    <label class="form-image">
      <span class="image-file"><i class="fas fa-paperclip"></i></span>
      <%= f.file_field :image, class:"hidden" %>
      </label>
      <%= f.text_area :content, class:"form-message" , placeholder:"type a message",id:"content"%>
      
    </div>
    <%=f.submit "送信", class:"form-submit"%>
  <%end%>
</div>

app/views/contacts/_side_bar.html.erb
<div class="side-bar">
<div class="side-bar-header">
  <div class="name">
    <%if teacher_signed_in?%>
       <div class= "current-chat-name"><i class="fas fa-comments"> students</i></div>
      <%elsif student_signed_in?%>
      <div class= "current-chat-name"><i class="fas fa-comments"> teacher</i></div>
      <%end%>
  </div>
  
</div>
 

<div class="rooms">
 <%if teacher_signed_in?%>
   <% current_teacher.teacher_rooms.reverse.each do |room|%>
    <div class="room">
      <div class="room-name">
        <%=link_to(room.name,teacher_room_contacts_path(room.id))%>
      </div>
    </div>
   <%end%>
 <%elsif student_signed_in? %>
    <% current_student.teacher_rooms.reverse.each do |room|%>
     <div class="room">
        <div class="room-name">
         <%=link_to(room.name,teacher_room_contacts_path(room.id))%>
        </div>
     </div>
    <%end%>
  <%end%>

</div>
<div class= "chat-edit">
  <div class="create-chat">
    <%=link_to("チャット作成",new_teacher_room_path)%>
  </div>
  <%if request.url.include?("contacts")%>
  <div class="delete-chat">
        <%=link_to("チャット削除",teacher_room_path(@teacher_room.id), method: :delete) %>
      </div>
        <%end%>
</div>
  </div>

app/views/contacts/index.html.erb
<div class= "wrapper">
<%=render "side_bar"%>
<%=render "main_chat"%>
</div>