config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :teachers, controllers: {
    sessions: "teachers/sessions",
    passwords:  'teachers/passwords',
    registrations: 'teachers/registrations'
  }
  devise_for :students, controllers: {
    sessions:      'students/sessions',
    passwords:     'students/passwords',
    registrations: 'students/registrations'
  }
  resources :teachers, only: [:edit,:update,:show]
  resources :students, only: [:edit,:update,:show,:index] do
    member do
    resources :student_records
    end
  end
  get 'messages/index'
  resources :rooms,only: [:index,:new,:create,:destroy] do
  resources :messages,only: [:new,:create,:index]
  end
  get 'contacts/index'
  resources :teacher_rooms,only: [:index,:new,:create,:destroy] do
    resources :contacts,only: [:new,:create,:index]
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>コネクト</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
   <%if student_signed_in? %>
  <div class="screen">
     <div class = "header-bar">
     <div class = "header-bar__left">
        <%=link_to root_path,class:"link-li" do%>
         <i class="fas fa-home" > home</i>
        <%end%>
        <%=link_to edit_student_path(current_student.id),class:"link-li" do%>
         <i class="fas fa-edit">edit</i>
        <%end%>
        <%=link_to rooms_path,class:"link-li" do%>
        <i class="fas fa-comments"> students</i>
        <%end%>
        <%=link_to teacher_rooms_path,class:"link-li" do%>
        <i class="fas fa-comments"> teacher</i>
        <%end%>
      </div>
      <div class= "header-bar__right">
         <%=image_tag current_student.image.variant(resize: '40x40') , class: "user-image" if current_student.image.attached?%>
         <%= link_to current_student.name,student_path(current_student.id)%>
      </div>
     </div>
     <div class= "wrap">
        <%= yield %>
     </div>
  </div>
  <%elsif teacher_signed_in? %>
  <div class="screen">
     <div class = "header-bar">
      <div class = "header-bar__left">
        <%=link_to root_path,class:"link-li" do%>
        <i class="fas fa-home"> home</i>
        <%end%>
        <%=link_to edit_teacher_path(current_teacher.id),class:"link-li" do %>
        <i class="fas fa-edit"> edit</i>
        <%end%>
        <%=link_to teacher_rooms_path,class:"link-li" do%>
        <i class="fas fa-comments"> chat</i>
        <%end%>
        <%=link_to students_path,class:"link-li" do%>
        <i class="fas fa-book-open"> students info</i>
        <%end%>
        </div>
         <div class= "header-bar__right">
         <%=image_tag current_teacher.image.icon.url , class: "user-image" if current_teacher.image?%>
         <%= link_to current_teacher.name,teacher_path(current_teacher.id)%>
      </div>
     </div>
     <div class= "wrap">
        <%= yield %>
     </div>
  </div>
  <%else%>
    <div class="screen">
     <div class = "header-bar">
         <div class = "header-bar__left">
         <%=link_to "コネクト", root_path, class:"app-name"%>
         </div>
         <div class= "header-bar__right">
            <p>生徒さん用：  </p>
               <%=link_to "ログイン",new_student_session_path,class:"link-li__logout"%>
               <%=link_to "新規登録",new_student_registration_path,class:"link-li__logout"%><span class="mg-15">／</span>
            <p>講師さん用：  </p>
               <%=link_to "ログイン",new_teacher_session_path,class:"link-li__logout"%>
               <%=link_to "新規登録",new_teacher_registration_path,class:"link-li__logout"%>
         </div>
         <i class="fas fa-bars" id = "fa-bars"></i>
      </div>
     <div class= "wrap">
      <div class = header-bar__pulldown id = "header-pulldown">
      <ul>
         <li>生徒さん用：  
               <%=link_to "ログイン",new_student_session_path,class:"link-li__logout"%>
               <%=link_to "新規登録",new_student_registration_path,class:"link-li__logout"%><span class="mg-15"></span>
         </li>
         <li>講師さん用：  
               <%=link_to "ログイン",new_teacher_session_path,class:"link-li__logout"%>
               <%=link_to "新規登録",new_teacher_registration_path,class:"link-li__logout"%>
         </li>
       </ul>
      </div>
        <%= yield %>
     </div>
  </div>
   <%end %>
  </body>
</html>